### ISSUE TITLE
ECMA Script RegEx reference

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-jadn#65]
Section 3.2.1.6 says "The pattern value SHOULD conform to the Pattern grammar of [ECMAScript] Section 21.2."

The References section cites ECMA-262 9th Edition, June 2018

The link redirects to 13th edition, June 2022.  In that edition, the Pattern grammar is in section **22.2**. The referenced location in the ECMA specification was correct for the 9th edition, but suggest that the 3.2.1.6 text and the reference section be updated to reflect the current (13th) edition and the correct location (section 22.2).

NOTE: based on their on-line archives, a new edition has been published annually since 2015.

**Comment by dlemire60** [comment]
At this point the current edition of ECMA Script is the 14th Edition, June 2023. Section 22.2 remains the current reference for regular expressions. That section includes the following note:

> The form and functionality of regular expressions is modelled after the regular expression facility in the Perl 5 programming language.

However, the ECMA Script standard seems like a better reference. Do we want to pin this reference to a specific edition or to the "RegExp (Regular Expression) Objects" section of the latest version of ECMA-262? Does OASIS have a convention for referring to the latest edition of a frequently updated standard?

**Comment by dlemire60** [comment]
Based on correspondence with OASIS TC Admin, the following would be an acceptable flexible reference format:

> [ECMAScript]
> ECMA International, "ECMAScript 2023 Language Specification", ECMA-262 14th Edition, June 2023, [https://www.ecma-international.org/ecma-262](https:/www.ecma-international.org/ecma-262) (or corresponding section(s) in current edition)

**Comment by davaya** [comment]
Closed by #83
